import sys,warnings,logging
warnings.filterwarnings("ignore"); logging.disable(logging.CRITICAL); sys.path.insert(0,".")
import chronoSIFT_v2_31 as M
rules=M._load_unique_yaml_mapping("rules/rules_evidence_calibrated_v23.yaml","rules")
weights=M._load_unique_yaml_mapping("rules/weights_evidence_calibrated_v21.yaml","weights")
emitted = M._collect_emitted_signals_from_rules(rules)
prof    = M._collect_profiling_output_signals(rules)
tin     = M._collect_temporal_input_signals(rules)
tout    = M._collect_temporal_rule_output_signals(rules)
maxs, w = M._parse_weights_policy(weights)
emitted=set(emitted); wk=set(w)
print(f"emitted signals (from rules)     : {len(emitted)}")
print(f"weighted signals (weights file)  : {len(wk)}")
print(f"max_event_score                  : {maxs}")
print(f"\nEMITTED BUT UNWEIGHTED (score contribution 0): {len(emitted-wk)}")
for s in sorted(emitted-wk)[:25]: print("   ", s)
print(f"\nWEIGHTED BUT NEVER EMITTED (dead weights): {len(wk-emitted)}")
for s in sorted(wk-emitted)[:25]: print("   ", s)
print(f"\ntemporal inputs not emitted anywhere: {sorted(set(tin)-emitted-set(tout))[:15]}")
